### ISSUE TITLE
Repo Access

### ISSUE THREAD

**Issue by leonardoaraujosantos** [PacktPublishing/Deep-Reinforcement-with-PyTorch-and-TensorFlow#1]
Hi @Mohammedyusufimaratwale I still don't have access to the repo

**Comment by Mohammedyusufimaratwale** [comment]
Hi Leonardo,


Thanks for letting me know.


The invitation to the repository has been sent to your email. I can also see that you are a member on the repository. Can you check if you have accepted the invitation?


Here is the link to the repository: https://github.com/PacktPublishing/Deep-Reinforcement-with-PyTorch-and-TensorFlow/settings/collaboration


I am sorry for the trouble.


Regards,

________________________________
